apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-data
  labels:
    type: local
    app: jenkins
    tiers: webapp
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/data1/jenkins-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-log
  labels:
    type: local
    app: jenkins
    tiers: webapp
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/data1/jenkins-log