version: '3'
volumes:
  jenkins-data:

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  jenkins:
    driver: bridge

services:
  jenkins:
    image: fjudith/jenkins:latest
    container_name: jenkins
    networks:
      - jenkins
    ports:
      - 58080:8080/tcp
      - 50000:50000/tcp
    environment:
      JAVA_OPTS: "-Xmx512m"
    volumes:
    - jenkins-data:/var/jenkins_home
  
  nginx:
    image: fjudith/jenkins:nginx
    container_name: nginx
    depends_on:
      - jenkins
    networks:
      - jenkins
      - traefik_proxy
    ports:
      - 50080:80/tcp